<Row@BoxLayout>

    Button:
        id: backtime_lbl
        size_hint_x: .1
        background_color: 0.141, 0.580, 0.956, 1

    Button:
        id: title_lbl
        font_size: 25
        size_hint_x: .3
        background_color: 0.141, 0.580, 0.956, 1

    Button:
        id: camera_lbl
        size_hint_x: .1
        background_color: 0.141, 0.580, 0.956, 1

    DrawingWidget:
        size_hint_x: .4
        id: drawingwidget

