ScreenManager:
    id: screen_manager

    MenuScreen
        id: menu_screen
        name: 'menu_screen'
        manager: 'screen_manager'

    CanvasScreen
        id: canvas_before
        name: 'canvas_before'
        manager: 'screen_manager'

    ImageScreen:
        id: image
        name: 'image'
        manager: 'screen_manager'


<MenuScreen@MDScreen>:
    MDBoxLayout
        MDRaisedButton:
            text: 'image'
            on_press: app.root.current = 'image'

        Widget

        MDRaisedButton:
            text: 'canvas.before'
            on_press: app.root.current = 'canvas_before'


<CanvasScreen@MDScreen>
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: app.dir_get('blur.png')

<ImageScreen@MDScreen>

    MDRaisedButton:
        on_press: app.dir_get('blur.png')
    Image:
        source: 'blur.png'
