#:include rows/row.kv

ScreenManager:
    id: screen_manager
    LoginScreen:
        id: login
        name: 'login'
        manager: 'screen_manager'
    MenuScreen:
        id: menu_screen
        name: 'menu'
        manager: 'screen_manager'
    LWRundown
        id: lw_rundown
        name: 'lw'
        manager: 'screen_manager'






<RundownTemplate@MDScreen>
    rundown: 'default'
    data: app.rvdata
    RecycleView
        id: rview
        data: root.data
        viewclass: 'Row'
        RecycleBoxLayout:
            id: rv
            default_size: None, dp(150)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'



<ThinGap@Widget>
    size_hint_y: None
    height: 3

<VertBox@MDBoxLayout>
    orientation: 'vertical'


<GMBToolbar@BoxLayout>
    size_hint_y: None
    height: 75
    Widget
    MDRaisedButton:
        text: '    0600    '
        on_press: app.root.current = '0600'
    Widget
    MDRaisedButton:
        text: '    0630    '
        on_press: app.root.current = '0630'
    Widget
    MDRaisedButton:
        text: '    0700    '
        on_press: app.root.current = '0700'
    Widget
    MDRaisedButton:
        text: '    0800    '
        on_press: app.root.current = '0800'
    Widget
    MDRaisedButton:
        text: '    0900    '
        on_press: app.root.current = '0900'
    Widget




<LoginScreen>
    MDBoxLayout:
        Widget:
            size_hint_x: .1

        VertBox:
            size_hint_x: .8
            MDLabel:
                text: 'Welcome to PiNews - Please login'
                halign: 'center'
            MDTextField:
                id: login
                font_size: 28
                hint_text: "USERNAME"
                mode: "rectangle"
            MDTextField:
                id: password
                font_size: 28
                hint_text: "PASSWORD"
                mode: "rectangle"
                password: True

            MDBoxLayout
                Widget
                MDRaisedButton:
                    text: 'CONNECT'
                    on_press: root.login(login.text, password.text)
                Widget
            Widget
                size_hint_y: 4

        Widget:
            size_hint_x: .1


<MenuScreen@MDScreen>:
    BoxLayout:
        orientation: 'vertical'
        MDToolbar:
            right_action_items: [["close", lambda x: app.stop()]]
            title: 'PiNews'
            size_hint_y: .1
        Widget:
            size_hint_y: .1

        MDLabel:
            text: 'CHOOSE A PRODUCTION'
            font_size: 40
            halign: 'center'
            size_hint_y: .1

        BoxLayout:
            size_hint_y: .1
            Widget:
            MDRaisedButton:
                text: '  GMB   '
                on_press: app.root.current = '0600'
            Widget:
            MDRaisedButton:
                text: '    LK    '
                on_press: app.root.current = 'lk'
            Widget:
            MDRaisedButton:
                text: '    TM    '
                on_press: app.root.current = 'tm'
            Widget
            MDRaisedButton:
                text: '    LW    '
                on_press: app.root.current = 'lw'
            Widget:

        BoxLayout:
            size_hint_y: .1
            Widget:
            MDRaisedButton:
                text: 'CSTM_1'
            Widget:
            MDRaisedButton:
                text: 'CSTM_2'
            Widget:
            MDRaisedButton:
                text: 'CSTM_3'
            Widget
            MDRaisedButton:
                text: 'CSTM_4'
            Widget:

        Widget:
            size_hint_y: .7



<LWRundown@MDScreen>
    RundownTemplate
        id: lw
        rundown: 'LW'
        data: app.rvdata
